language: php

sudo: false

php:
    - 7.0
    - hhvm

matrix:
    fast_finish: true

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini || true

before_script:
    - composer --prefer-source update

script: ./vendor/bin/phpunit
